"""Initial schema - all 32 tables

Revision ID: fe986d4c0a6a
Revises: 
Create Date: 2025-12-08 15:40:07.104947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe986d4c0a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('decision_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_made', sa.String(length=50), nullable=False),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('was_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decision_logs_created_at'), 'ai_decision_logs', ['created_at'], unique=False)
    op.create_table('ai_learning_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('human_validated', sa.Boolean(), nullable=False),
    sa.Column('human_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_learning_events_created_at'), 'ai_learning_events', ['created_at'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_created_at'), 'fx_rates', ['created_at'], unique=False)
    op.create_index(op.f('ix_fx_rates_from_currency'), 'fx_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_to_currency'), 'fx_rates', ['to_currency'], unique=False)
    op.create_table('ngos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metric_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_metrics_created_at'), 'system_health_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_health_metrics_metric_name'), 'system_health_metrics', ['metric_name'], unique=False)
    op.create_table('task_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('action_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('was_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_activity_logs_admin_id'), 'admin_activity_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_created_at'), 'admin_activity_logs', ['created_at'], unique=False)
    op.create_table('ai_context_store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=100), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_context_store_user_id'), 'ai_context_store', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('context_type', sa.String(length=100), nullable=False),
    sa.Column('conversation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('impact_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IMPLEMENTED', name='aiproposalstatusenum'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_earning_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_earned_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_earning_stats_date'), 'daily_earning_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_earning_stats_user_id'), 'daily_earning_stats', ['user_id'], unique=False)
    op.create_table('liveness_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('verification_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liveness_verifications_user_id'), 'liveness_verifications', ['user_id'], unique=False)
    op.create_table('ngo_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('social_impact_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('beneficiaries_count', sa.Integer(), nullable=False),
    sa.Column('impact_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngo_projects_ngo_id'), 'ngo_projects', ['ngo_id'], unique=False)
    op.create_table('payout_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method_type', sa.Enum('WAVE_MONEY', 'KBZ_PAY', 'CB_PAY', 'AYA_PAY', 'ONEPAY', 'PAYPAL', 'WESTERN_UNION', 'MONEYGRAM', 'BANK_TRANSFER', name='payoutmethodenum'), nullable=False),
    sa.Column('method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_methods_user_id'), 'payout_methods', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_partner_id'), 'projects', ['partner_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriorityenum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatusenum'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('ai_handled', sa.Boolean(), nullable=False),
    sa.Column('ticket_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('EARNING', 'WITHDRAWAL', 'BONUS', 'PENALTY', 'REFUND', name='transactiontypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatusenum'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('trans_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=True),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_created_at'), 'user_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_fingerprint')
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pending_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_local', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('payout_method', sa.Enum('WAVE_MONEY', 'KBZ_PAY', 'CB_PAY', 'AYA_PAY', 'ONEPAY', 'PAYPAL', 'WESTERN_UNION', 'MONEYGRAM', 'BANK_TRANSFER', name='payoutmethodenum'), nullable=False),
    sa.Column('payout_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatusenum'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_created_at'), 'withdrawals', ['created_at'], unique=False)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('biometric_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('verification_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_verifications_user_id'), 'biometric_verifications', ['user_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_ai_response', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('logged_out_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('withdrawal_fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('withdrawal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fee_amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_fees_user_id'), 'withdrawal_fees', ['user_id'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignments_task_id'), 'task_assignments', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_user_id'), 'task_assignments', ['user_id'], unique=False)
    op.create_table('earning_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('base_reward', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quality_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('speed_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('streak_bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tier_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earning_history_earned_at'), 'earning_history', ['earned_at'], unique=False)
    op.create_index(op.f('ix_earning_history_user_id'), 'earning_history', ['user_id'], unique=False)
    op.drop_index('ix_daily_earning_summaries_date', table_name='daily_earning_summaries')
    op.drop_table('daily_earning_summaries')
    op.drop_index('ix_user_goals_user_id', table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index('ix_user_languages_user_id', table_name='user_languages')
    op.drop_table('user_languages')
    op.drop_table('ngo_sponsors')
    op.drop_index('ix_revenue_ledger_source', table_name='revenue_ledger')
    op.drop_index('ix_revenue_ledger_transaction_date', table_name='revenue_ledger')
    op.drop_table('revenue_ledger')
    op.drop_index('ix_payment_methods_user_id', table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_table('partner_transactions')
    op.drop_table('user_subsidies')
    op.drop_index('ix_wallet_ledger_created_at', table_name='wallet_ledger')
    op.drop_index('ix_wallet_ledger_user_id', table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_withdraw_requests_requested_at', table_name='withdraw_requests')
    op.drop_index('ix_withdraw_requests_user_id', table_name='withdraw_requests')
    op.drop_table('withdraw_requests')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('data_sales')
    op.add_column('submissions', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('submissions', sa.Column('ai_validation_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('submissions', sa.Column('ai_validation_notes', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('ai_auto_approved', sa.Boolean(), nullable=False))
    op.add_column('submissions', sa.Column('human_review_notes', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('submissions', sa.Column('completion_time_seconds', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('submissions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('submissions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', name='submissionstatusenum'),
               nullable=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_submissions_submitted_at', table_name='submissions')
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.drop_constraint('submissions_task_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_user_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('submissions', 'earned_usd')
    op.drop_column('submissions', 'submission_data')
    op.drop_column('submissions', 'final_payout_usd')
    op.drop_column('submissions', 'bonus_multiplier')
    op.add_column('tasks', sa.Column('project_id', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('task_type', sa.Enum('IMAGE_LABELING', 'TEXT_ANNOTATION', 'AUDIO_TRANSCRIPTION', 'VIDEO_REVIEW', 'DATA_VALIDATION', 'CONTENT_MODERATION', 'SURVEY', 'OTHER', name='tasktypeenum'), nullable=False))
    op.add_column('tasks', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXPERT', name='taskdifficultyenum'), nullable=False))
    op.add_column('tasks', sa.Column('reward_usd', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('tasks', sa.Column('expected_time_seconds', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('example_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('metadata_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('validation_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('max_submissions', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('current_submissions', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_tasks_category', table_name='tasks')
    op.drop_index('ix_tasks_code', table_name='tasks')
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'language_code')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'expected_time_sec')
    op.drop_column('tasks', 'payout_usd')
    op.drop_column('tasks', 'code')
    op.drop_column('tasks', 'dialect')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', 'PARTNER', 'NGO', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_earnings_usd', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('users', sa.Column('available_balance_usd', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('users', sa.Column('pending_balance_usd', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('users', sa.Column('lifetime_withdrawals_usd', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('users', sa.Column('preferred_currency', sa.String(length=3), nullable=False))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=5), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('kyc_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('kyc_verified_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('current_streak_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('longest_streak_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_task_completed_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'face_embedding_b64')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_embedding_b64', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.Enum('FREE', 'PRO', 'PREMIUM', name='subscriptiontier'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'user_metadata')
    op.drop_column('users', 'last_task_completed_date')
    op.drop_column('users', 'longest_streak_days')
    op.drop_column('users', 'current_streak_days')
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'kyc_verified_at')
    op.drop_column('users', 'kyc_data')
    op.drop_column('users', 'kyc_verified')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'preferred_currency')
    op.drop_column('users', 'lifetime_withdrawals_usd')
    op.drop_column('users', 'pending_balance_usd')
    op.drop_column('users', 'available_balance_usd')
    op.drop_column('users', 'total_earnings_usd')
    op.drop_column('users', 'subscription_started_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    op.add_column('tasks', sa.Column('dialect', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('payout_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('expected_time_sec', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.create_index('ix_tasks_code', 'tasks', ['code'], unique=False)
    op.create_index('ix_tasks_category', 'tasks', ['category'], unique=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'current_submissions')
    op.drop_column('tasks', 'max_submissions')
    op.drop_column('tasks', 'validation_criteria')
    op.drop_column('tasks', 'metadata_required')
    op.drop_column('tasks', 'example_data')
    op.drop_column('tasks', 'instructions')
    op.drop_column('tasks', 'expected_time_seconds')
    op.drop_column('tasks', 'reward_usd')
    op.drop_column('tasks', 'difficulty')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'project_id')
    op.add_column('submissions', sa.Column('bonus_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('final_payout_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('submission_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('earned_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_user_id_fkey', 'submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('submissions_task_id_fkey', 'submissions', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.create_index('ix_submissions_submitted_at', 'submissions', ['submitted_at'], unique=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('submissions', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FLAGGED', name='submissionstatusenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('submissions', 'updated_at')
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'completion_time_seconds')
    op.drop_column('submissions', 'reviewed_by')
    op.drop_column('submissions', 'human_review_notes')
    op.drop_column('submissions', 'ai_auto_approved')
    op.drop_column('submissions', 'ai_validation_notes')
    op.drop_column('submissions', 'ai_validation_score')
    op.drop_column('submissions', 'data')
    op.create_table('data_sales',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sale_price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('platform_revenue_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_bonus_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sold_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='data_sales_submission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='data_sales_pkey')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('TASK_APPROVED', 'TASK_REJECTED', 'PAYMENT_RECEIVED', 'WITHDRAWAL_COMPLETE', 'WITHDRAWAL_PENDING', 'NEW_TASK_MATCH', 'SUBSCRIPTION_EXPIRING', 'SUBSCRIPTION_UPGRADED', 'DAILY_LIMIT_REACHED', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_read', 'notifications', ['read'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_table('withdraw_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fee_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net_amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payment_method_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payment_account', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name='withdraw_requests_payment_method_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='withdraw_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='withdraw_requests_pkey')
    )
    op.create_index('ix_withdraw_requests_user_id', 'withdraw_requests', ['user_id'], unique=False)
    op.create_index('ix_withdraw_requests_requested_at', 'withdraw_requests', ['requested_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('monthly_price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_table('wallet_ledger',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('balance_after_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallet_ledger_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_ledger_pkey')
    )
    op.create_index('ix_wallet_ledger_user_id', 'wallet_ledger', ['user_id'], unique=False)
    op.create_index('ix_wallet_ledger_created_at', 'wallet_ledger', ['created_at'], unique=False)
    op.create_table('user_subsidies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sponsor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subsidy_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['ngo_sponsors.id'], name='user_subsidies_sponsor_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subsidies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_subsidies_pkey')
    )
    op.create_table('partner_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('partner_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('partner_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('revenue_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_payout_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('platform_cut_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='partner_transactions_pkey')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('method_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_identifier', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_methods_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_methods_pkey')
    )
    op.create_index('ix_payment_methods_user_id', 'payment_methods', ['user_id'], unique=False)
    op.create_table('revenue_ledger',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='revenue_ledger_pkey')
    )
    op.create_index('ix_revenue_ledger_transaction_date', 'revenue_ledger', ['transaction_date'], unique=False)
    op.create_index('ix_revenue_ledger_source', 'revenue_ledger', ['source'], unique=False)
    op.create_table('ngo_sponsors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('funding_amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('funding_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('funding_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_subsidy_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ngo_sponsors_pkey')
    )
    op.create_table('user_languages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('proficiency', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_languages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_languages_pkey')
    )
    op.create_index('ix_user_languages_user_id', 'user_languages', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='goalperiod'), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_goals_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_goals_pkey')
    )
    op.create_index('ix_user_goals_user_id', 'user_goals', ['user_id'], unique=False)
    op.create_table('daily_earning_summaries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tasks_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earned_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('auto_cut_applied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_cut_amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_earning_summaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_earning_summaries_pkey')
    )
    op.create_index('ix_daily_earning_summaries_date', 'daily_earning_summaries', ['date'], unique=False)
    op.drop_index(op.f('ix_earning_history_user_id'), table_name='earning_history')
    op.drop_index(op.f('ix_earning_history_earned_at'), table_name='earning_history')
    op.drop_table('earning_history')
    op.drop_index(op.f('ix_task_assignments_user_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_task_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_withdrawal_fees_user_id'), table_name='withdrawal_fees')
    op.drop_table('withdrawal_fees')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_biometric_verifications_user_id'), table_name='biometric_verifications')
    op.drop_table('biometric_verifications')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_created_at'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_created_at'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_projects_partner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_payout_methods_user_id'), table_name='payout_methods')
    op.drop_table('payout_methods')
    op.drop_index(op.f('ix_ngo_projects_ngo_id'), table_name='ngo_projects')
    op.drop_table('ngo_projects')
    op.drop_index(op.f('ix_liveness_verifications_user_id'), table_name='liveness_verifications')
    op.drop_table('liveness_verifications')
    op.drop_index(op.f('ix_daily_earning_stats_user_id'), table_name='daily_earning_stats')
    op.drop_index(op.f('ix_daily_earning_stats_date'), table_name='daily_earning_stats')
    op.drop_table('daily_earning_stats')
    op.drop_table('ai_proposals')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_ai_context_store_user_id'), table_name='ai_context_store')
    op.drop_table('ai_context_store')
    op.drop_index(op.f('ix_admin_activity_logs_created_at'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_admin_id'), table_name='admin_activity_logs')
    op.drop_table('admin_activity_logs')
    op.drop_table('task_types')
    op.drop_index(op.f('ix_system_health_metrics_metric_name'), table_name='system_health_metrics')
    op.drop_index(op.f('ix_system_health_metrics_created_at'), table_name='system_health_metrics')
    op.drop_table('system_health_metrics')
    op.drop_table('sponsors')
    op.drop_table('partners')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_fx_rates_to_currency'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_from_currency'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_created_at'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_ai_learning_events_created_at'), table_name='ai_learning_events')
    op.drop_table('ai_learning_events')
    op.drop_index(op.f('ix_ai_decision_logs_created_at'), table_name='ai_decision_logs')
    op.drop_table('ai_decision_logs')
    # ### end Alembic commands ###
