"""baseline reset

Revision ID: 38ef6cc6e7fb
Revises: 
Create Date: 2025-11-17 18:11:02.121522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migrations.helpers import drop_index_if_exists
drop_index_if_exists("ix_tasks_pool_natural_key", "tasks_pool")


# revision identifiers, used by Alembic.
revision: str = '38ef6cc6e7fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('display_value_usd', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('expected_time_sec', sa.Integer(), server_default='60', nullable=False),
    sa.Column('expected_confidence', sa.Integer(), server_default='66', nullable=False),
    sa.Column('usd_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('user_actions_json', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'code', name='uq_daily_tasks_date_code')
    )
    op.create_index('ix_daily_tasks_category', 'daily_tasks', ['category'], unique=False)
    op.create_index('ix_daily_tasks_code', 'daily_tasks', ['code'], unique=False)
    op.create_index('ix_daily_tasks_date', 'daily_tasks', ['date'], unique=False)
    op.create_table('earn_daily_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earn_daily_sessions_user_id'), 'earn_daily_sessions', ['user_id'], unique=False)
    op.create_table('face_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_profiles_user_id'), 'face_profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wallet_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_ledger_ref', 'wallet_ledger', ['ref'], unique=False)
    op.create_index('ix_wallet_ledger_user_id', 'wallet_ledger', ['user_id'], unique=False)
    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdraw_requests_ref'), 'withdraw_requests', ['ref'], unique=False)
    op.create_index(op.f('ix_withdraw_requests_user_id'), 'withdraw_requests', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token'), 'auth_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_withdraw_requests_user_id'), table_name='withdraw_requests')
    op.drop_index(op.f('ix_withdraw_requests_ref'), table_name='withdraw_requests')
    op.drop_table('withdraw_requests')
    op.drop_index('ix_wallet_ledger_user_id', table_name='wallet_ledger')
    op.drop_index('ix_wallet_ledger_ref', table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_face_profiles_user_id'), table_name='face_profiles')
    op.drop_table('face_profiles')
    op.drop_index(op.f('ix_earn_daily_sessions_user_id'), table_name='earn_daily_sessions')
    op.drop_table('earn_daily_sessions')
    op.drop_index('ix_daily_tasks_date', table_name='daily_tasks')
    op.drop_index('ix_daily_tasks_code', table_name='daily_tasks')
    op.drop_index('ix_daily_tasks_category', table_name='daily_tasks')
    op.drop_table('daily_tasks')
    # ### end Alembic commands ###
