# config/confidence_policy.yaml
version: 1
confidence:
  high: 0.80
  medium: 0.55
actions:
  on_high: pass
  on_medium: add_caution
  on_low: fallback
fallback:
  route: "admin_review"   # recorded, not auto-routed to human yet
signals:
  enable_emotion_intent: true
  enable_token_focus: true
telemetry:
  write_runtime_files: true
  log_level: "INFO"
